version: '3.3'

services:
  web:
    command: ["bash", "scripts/run.sh"]
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - nginx_network

  db:
    image: postgres:latest
    env_file:
      - .env
    environment:
      POSTGRES_USER: postgres  # Ensure the default user is created
      POSTGRES_PASSWORD: marine@cusat  # The password for the postgres user
      POSTGRES_DB: marine_db  # The database to be created
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nginx_network
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always  # Ensure the container restarts if it fails


  redis:
    image: redis:latest
    networks:
      - nginx_network

  nginx:
    image: nginx:latest
    ports:
      - "99:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./staticfiles:/code/staticfiles
      - ./media:/code/media
    depends_on:
      - web
    networks:
      - nginx_network

volumes:
  postgres_data:
  pgadmin_data:
  metabase_data:

networks:
  nginx_network:
