version: '3.3'

services:
  web:
    command: ["bash", "scripts/run.sh"]
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - nginx_network

  db:
    image: postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nginx_network

  redis:
    image: redis:latest
    networks:
      - nginx_network

  nginx:
    image: nginx:latest
    ports:
      - "99:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./staticfiles:/code/staticfiles
      - ./media:/code/media
    depends_on:
      - web
    networks:
      - nginx_network

volumes:
  postgres_data:
  pgadmin_data:
  metabase_data:

networks:
  nginx_network:
